### ISSUE TITLE
No module named image_processing

### ISSUE THREAD

**Issue by Dominic-DallOsto** [QVPR/teach-repeat#27]
When trying to run any of the launch files requiring the `image_processing` module, the following error is encountered:

```bash
Traceback (most recent call last):
  File "/home/dominic/teach-repeat/catkin_ws/devel/lib/teach_repeat/camera_calibrator.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/dominic/teach-repeat/catkin_ws/src/teach-repeat/nodes/camera_calibrator.py", line 12, in <module>
    import image_processing
ModuleNotFoundError: No module named 'image_processing'
```

Tested with Ubuntu 20.04, ROS Noetic.

**Comment by Tobias-Fischer** [comment]
Fixed in #28
